[module]
name = "statmodule"
version = "0.1.0"
description = "Collection of statistical methods in `{box}` module form in R"
authors = [
    { name = "Joshua Marie", email = "joshua.marie.k@gmail.com" },
]
license = "mit"
r_version = "4.0.0"
src = "fastnum/"                 # The module is renamed, keep this temporarily

[package_deps]
rlang = ">=1.1.0"

[module_deps]

[native]
paths = ["cpp/", "random/core-cpp/"]         
build_deps = { Rcpp = "*", BH = "*", dqrng = "*" }

[test]
framework = "testthat"
dir = "tests"
