[module]
name = "statmodule"
version = "0.1.0"
description = "Collection of statistical methods in R. This is a `{box}` module and can be only attached through `box::use()`, not on any means like `library()`. "
authors = [
    { name = "Joshua Marie", email = "joshua.marie.k@gmail.com" },
]
license = "mit"
r_version = "4.0.0"
# src = "statmodule/"                 

[package_deps]
rlang = ">=1.1.0"
tabstats = ">=0.2.1"
cli = ">=3.6.3"
purrr = "*"
dplyr = ">=1.1.0"
tidyselect = "*"

[module_deps]

[native]
path = ["random/core-cpp/", "regression/src"]         

[native.build_deps]
Rcpp = "*"
RcppEigen = "*"
BH = "*"
dqrng = "*"

# [test]
# framework = "testthat"
# dir = "tests"
